---
apiVersion: v1
kind: Service
metadata:
  name: aad-id-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aad-id-service
---
apiVersion: v1
kind: Pod
metadata:
  name: aad-id-service-pod
  labels:
    app: aad-id-service
    platform: csharp
spec:
  containers:
  - name: api-container
    image: vplauzon/aad-pod-id-svc
    ports:
    - containerPort: 80
    env:
    - name: TENANT_ID
      value: "51df06a3-27ed-4987-85b6-f9018ad9c7b9"
    - name: APPLICATION_ID
      value: "27f7ac24-3757-48a8-be55-65f5469d0d3b"
