apiVersion: v1
kind: Pod
metadata:
  name: keyvaultdemo
  labels:
    aadpodidbinding: pod-selector-label
spec:
  containers:
    - name: keyvaultdemo
      image: robinmanuelthiel/azurekeyvaulttester:latest
      env:
        - name: AzureKeyVaultUri
          value: https://test-vault-1a.vault.azure.net/
        - name: TestSecretId
          value: secret1
